name: 'LLM AI Code Reviewer Action'
description:
  'Smart AI Code Reviewer that support multiple AI providers (Currently support
  Groq and Gemini).'
author: 'galihlprakoso'

branding:
  icon: 'code'
  color: 'purple'

inputs:
  ai_provider:
    description: 'AI providers (available values: GEMINI, GROQ)'
    required: true
    default: 'GROQ'
  ai_provider_model:
    description: 'AI models based on selected provider.'
    required: true
    default:
  codebase_high_overview_descripton:
    description:
      'Please give high overview about the codebase (e.g framework used, design
      pattern, business context, etc.)'
    required: true
  max_tools_node_recursion:
    description:
      'Please give high overview about the codebase (e.g framework used, design
      pattern, business context, etc.)'
    default: 1
  GITHUB_WORKSPACE:
    description: 'just pass the github.workspace value'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token to interact with the repository.'
    required: true
  GOOGLE_GEMINI_API_KEY:
    description:
      'Google Gemini API Key. See more:
      https://ai.google.dev/gemini-api/docs/api-key'
    required: false
  GROQ_API_KEY:
    description: 'Groq API Key. Generate here: https://console.groq.com/keys'
    required: false
  TAVILY_API_KEY:
    description:
      'Tavily Search API Key. Generate here: https://app.tavily.com/home'
    required: false

runs:
  using: node20
  main: dist/index.js
